version: 2.1

jobs:
  node-job:
    docker:
      - image: cimg/android:2024.01-node

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y unzip

      - run:
          name: Install npm packages
          command: npm ci

      - run:
          name: Install Allure
          command: npm install -g allure-commandline --unsafe-perm

      - run:
          name: Run tests
          command: npx cypress run

      - run:
          name: Generate report
          command: npm run allure:report

      - store_artifacts:
          path: allure-report
          destination: CypressReport

workflows:
  build-and-test:
    jobs:
      - node-job